add libcsp to pico project
spacecubics/scsat1-rpi pull request #34
Opened 2024-07-02 15:46 UTC by KantaTamura

libcspをrpi_picoのプロジェクトに追加

libcsp zephyr uart driverを用いたサンプルプログラムをいくつか追加
- `csp-send`: CSPv1を用いて "hello world" を送信する
- `csp-server`: CSPv1を用いたserver

2024-07-03 08:29 UTC, sasataku commented
同じ `uart1.overlay` などが複数のDIrectoryに分散して存在しているので、どこかにまとめられないかな？

2024-07-03 08:42 UTC, sasataku requested changes

2024-07-03 08:42 UTC, sasataku commented on pico/sample/csp-send/src/main.c
> +	default_iface->addr = 2;
CSPのアドレスは、zero側と合わせて、ひとまず  `13` に統一して、`#define` で上にもっていきましょう
https://github.com/spacecubics/scsat1-rpi/blob/main/zero/meta-scsat1-rpi/conf/distro/include/scsat1-rpi-variables.inc#L3

2024-07-03 08:42 UTC, sasataku commented on pico/sample/csp-server/src/main.c
> +	default_iface->addr = 14;
CSPのアドレスは、zero側と合わせて、ひとまず  `13` に統一して、`#define` で上にもっていきましょう
https://github.com/spacecubics/scsat1-rpi/blob/main/zero/meta-scsat1-rpi/conf/distro/include/scsat1-rpi-variables.inc#L3

2024-07-03 08:46 UTC, sasataku commented on pico/sample/csp-send/src/main.c
> +	default_iface->addr = 2;
こっちのbranchに合わせて `14` にしようか
https://github.com/spacecubics/scsat1-rpi/compare/main...KantaTamura:scsat1-rpi:wip/routing-csp

2024-07-03 08:46 UTC, sasataku commented on pico/sample/csp-server/src/main.c
> +	default_iface->addr = 14;
このbranchに合わせて `14` にしているのだと理解したのでそのままでOKです。

2024-07-03 11:13 UTC, KantaTamura commented
> 同じ uart1.overlay などが複数のDIrectoryに分散して存在しているので、どこかにまとめられないかな？
これは他のサンプルも含めてどうにかしようとしていたので，別のPRに分けます！

2024-07-03 11:21 UTC, KantaTamura commented on pico/sample/csp-send/src/main.c
> +	default_iface->addr = 2;
`CSP_SRC_ADDR` と `CSP_DST_ADDR` を定義し，最新のzeroのrouterの設定に合わせてそれぞれ `14` と `13` にしています

2024-07-03 11:21 UTC, KantaTamura commented on pico/sample/csp-server/src/main.c
> +	default_iface->addr = 14;
上と同様にしています

2024-07-03 11:23 UTC, KantaTamura commented
libcspの方で，`CONFIG_LIBCSP_HAVE_STDIO` が無くなるので，libcspのほうがマージされたら変更します

2024-07-04 05:03 UTC, sasataku commented
Thanks.LGTM.

2024-07-04 05:04 UTC, sasataku approved these changes

2024-07-04 05:05 UTC, merged