Add routing func to csp_handler
spacecubics/scsat1-rpi pull request #35
Opened 2024-07-03 14:01 UTC by KantaTamura

`csp_handler` に下記のようなアドレスが割り振られたネットワーク上のパケットをルーティングする機能を追加
```
┌─────────────┐
│             │
│     OBC     │
│             │
└────┬───┬────┘
     └───┘ can0 - 11
       ┃
       ┃ <CAN bus>
       ┃
     ┌───┐ can0 - 12
┌────┴───┴────┐
│             │
│     ZERO    │
│             │
└────┬───┬────┘
     └───┘ /dev/ttyS0 - 13
       ┃
       ┃ <UART>
       ┃
     ┌───┐ UART0 - 14
┌────┴───┴────┐
│             │
│     PICO    │
│             │
└─────────────┘
```

2024-07-04 03:33 UTC, yashi requested changes

2024-07-04 03:33 UTC, yashi commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add KISS interface [/dev/ttyS0], error: %d\n", error);
`/dev/ttyS0` は、  `usart_conf.device` から取ったら？

2024-07-04 03:33 UTC, yashi commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add CAN interface [can0]");
Linux側 も Zephyr側も、 アプリでは `csp_print()` を使わないようにしよう。 `csp_print()` は libcsp 内部で `printf()` や logging を抽象化するためだけに存在するという考え。

Zephyr の方は logging subsys があるから良いけど、 Linuxはどうしようかね....。

あ、このPRで直さなくても良いよ。別 issue で OK

2024-07-04 03:33 UTC, yashi commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +	int error = csp_usart_open_and_add_kiss_interface(&usart_conf, CSP_IF_KISS_DEFAULT_NAME,
できれば、この関数を使わないで欲しいかな。 1) APIがすきじゃない。 2) API修正する予定。 

名前だけ変えた dead copy をこっちに持ってきても良いと思う。修正は、この PRじゃなくても良い

2024-07-04 03:33 UTC, yashi commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +	if (CSP_USE_RTABLE) {
アプリでは Routing 必須なので、 `if` いらんのでは？

2024-07-04 06:32 UTC, KantaTamura commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add CAN interface [can0]");
`csp_print` だと `jounalctl` でログが見れなかったので，systemdにしたときにログを出せるようにしないといけないな...とは思ってました．

2024-07-04 06:32 UTC, KantaTamura commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +	if (CSP_USE_RTABLE) {
たしかに，そうですね．

2024-07-04 06:56 UTC, yashi commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add CAN interface [can0]");
え？見えるのでは？ `stdout` に書いたら、 journald で拾ってくれない？ native protocol ではないけど

2024-07-04 07:06 UTC, KantaTamura commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add CAN interface [can0]");
宛先をzeroにしてCSPパケット送ったときに， `Hello World A` とかが出てなかった気がします

2024-07-04 09:06 UTC, yashi commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add CAN interface [can0]");
これで出たよ？
```
❯ cat a.sh
#!/bin/bash

while true;
do
    echo "hello world"
    sleep 30
done

❯ cat hello.service
[Unit]
Description=Hello World Service
After=systend-user-sessions.service

[Service]
Type=simple
ExecStart=/tmp/a.sh

❯ sudo ln -s /tmp/hello.service  /etc/systemd/system/
❯ systemctl daemon-reload
❯ systemctl start hello
```
```
❯ journalctl -f
Jul 04 18:04:45 x570 a.sh[171839]: hello world
```

2024-07-04 10:40 UTC, sasataku requested changes

2024-07-04 10:40 UTC, sasataku commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add KISS interface [%s], error: %d\n", usart_conf.device,
実機で試したら、以下のエラーが発生
```
root@raspberrypi0-2w-64:~# csp_handler 
INIT CAN: device: [can0], bitrate: 1000000, promisc: 1
csp_usart_open: failed to open device: [/dev/ttyS0], errno: No such file or directory
failed to add KISS interface [/dev/ttyS0], error: -2
```
`/dev/ttyS0` がいなかったので、`/boot/config.txt` に `enable_uart=1` を追加したら成功。
レシピに設定抜けてる？

2024-07-04 10:56 UTC, KantaTamura commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add CAN interface [can0]");
調べてると，できるっぽいので
zeroに送ってるつもりが，picoに送っていて，何も表示されてなかった可能性も...

家に帰ってから試してみます！

2024-07-04 10:56 UTC, KantaTamura commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add KISS interface [%s], error: %d\n", usart_conf.device,
あ... `local.conf` に入れてました...

2024-07-04 11:21 UTC, sasataku commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add KISS interface [%s], error: %d\n", usart_conf.device,
Yoctoあるある(build配下を直接直して、sampleに入れ忘れる)
で、細かいんだけど `enable_uart=1` のcommitの順番は、 f5f886dd5 よりも前にしてもらえる？
(基本、commit単位でエラーにならないようにするため)

2024-07-04 11:39 UTC, yashi commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add KISS interface [%s], error: %d\n", usart_conf.device,
> 基本、commit単位でエラーにならないように

bisection できるようにだね

2024-07-04 11:41 UTC, yashi commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add CAN interface [can0]");
たぶんなんか勘違いしている

2024-07-04 11:53 UTC, sasataku commented
実機で試して、Zero、Picoともに、PCからのping/uptime要求に対して応答が返ることを確認。
Good Job!

12 = Zero
14 = Pico

```
[satctl] csp ping 12
Reply in 2.134 ms
[satctl] csp ping 14
Reply in 4.398 ms
[satctl] csp uptime 12
53 seconds
[satctl] csp uptime 14
59 seconds
```

2024-07-04 12:04 UTC, KantaTamura commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add KISS interface [%s], error: %d\n", usart_conf.device,
> enable_uart=1 のcommitの順番は、 https://github.com/spacecubics/scsat1-rpi/commit/f5f886dd59fe6833ee61072ab0a87e3cfc6fe9fa よりも前にしてもらえる？

あれ？なってないですか？
serial-gettyの前に入れてるはずですが...

2024-07-04 12:16 UTC, sasataku commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add KISS interface [%s], error: %d\n", usart_conf.device,
すまぬ、、見誤った・・

2024-07-04 12:20 UTC, sasataku approved these changes
LGTM

2024-07-05 00:50 UTC, sasataku commented on zero/meta-csp/recipes-cspd/csp-handler/files/main.c
> +		csp_print("failed to add CAN interface [can0]");
csp_print()で、`journalctl` でログ見れてます

```
Apr 28 17:42:29 raspberrypi0-2w-64 csp_handler[191]: failed to add CAN interface [can0]
```

2024-07-05 01:06 UTC, yashi approved these changes

2024-07-05 01:07 UTC, merged